//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS_OJEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS_OJEADOS()
        {
            this.TEMPORADAS_EMPLEADOS = new HashSet<TEMPORADAS_EMPLEADOS>();
        }
    
        public string DNI { get; set; }
        public string Formacion { get; set; }
        public string Experiencia { get; set; }
    
        public virtual OJEADOS OJEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORADAS_EMPLEADOS> TEMPORADAS_EMPLEADOS { get; set; }
    }
}
