//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUGADORES_OJEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JUGADORES_OJEADOS()
        {
            this.TEMPORADAS_JUGADORES = new HashSet<TEMPORADAS_JUGADORES>();
        }
    
        public string DNI { get; set; }
        public string Posicion { get; set; }
        public string PiernaDominante { get; set; }
        public Nullable<decimal> ValorDeMercado { get; set; }
        public Nullable<System.DateTime> VencimientoContrato { get; set; }
        public Nullable<short> Altura { get; set; }
        public Nullable<short> Peso { get; set; }
        public Nullable<bool> EnPrestamo { get; set; }
    
        public virtual OJEADOS OJEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORADAS_JUGADORES> TEMPORADAS_JUGADORES { get; set; }
    }
}
