//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OJEADOS
    {
        public string DNI { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Correo { get; set; }
        public Nullable<short> AnhoNacimiento { get; set; }
        public Nullable<short> Valoracion { get; set; }
        public string Foto { get; set; }
        public Nullable<int> IdClub { get; set; }
        public string Club { get; set; }
        public string Pasaporte { get; set; }
        public string PaisNacimiento { get; set; }
    
        public virtual CLUB CLUB1 { get; set; }
        public virtual EMPLEADOS_OJEADOS EMPLEADOS_OJEADOS { get; set; }
        public virtual JUGADORES_OJEADOS JUGADORES_OJEADOS { get; set; }
    }
}
