//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORADAS_EMPLEADOS
    {
        public string DNI { get; set; }
        public string Temporada { get; set; }
        public Nullable<short> PartidosJugados { get; set; }
        public Nullable<short> Victorias { get; set; }
        public Nullable<short> Derrotas { get; set; }
        public Nullable<short> Empates { get; set; }
        public Nullable<short> Puntos { get; set; }
        public Nullable<short> Competicion { get; set; }
        public string Club { get; set; }
    
        public virtual EMPLEADOS_OJEADOS EMPLEADOS_OJEADOS { get; set; }
    }
}
