//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORADAS_JUGADORES
    {
        public string DNI { get; set; }
        public string Temporada { get; set; }
        public string Club { get; set; }
        public string Competicion { get; set; }
        public Nullable<short> PartidosTitular { get; set; }
        public Nullable<short> PartidosSuplente { get; set; }
        public Nullable<short> PartidosConvocado { get; set; }
        public Nullable<short> MinutosJugados { get; set; }
        public Nullable<short> Goles { get; set; }
        public Nullable<short> TarjetasAmarillas { get; set; }
        public Nullable<short> TarjetasRojas { get; set; }
    
        public virtual JUGADORES_OJEADOS JUGADORES_OJEADOS { get; set; }
    }
}
